### ISSUE TITLE
Option to delete the backups in browser?

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/tackup#4]
Been using this for a while after losing 600+ tabs on a hard crash, and so far it's been working pretty well. One problem I've got is that I can't delete the backups on-demand. Would you consider adding a function to remove backups on-demand or automatically delete them after a set interval? Clearing the browser history seems pointless if I can't erase the backups as well.

**Comment by nabijaczleweli** [comment]
Sorry for the delay, I just got back from hospital. Yes, that's probably entirely feasible, I'll see what I can magic up.

**Comment by nabijaczleweli** [comment]
Okay, I've added both the functions you suggested to [current master](https://github.com/nabijaczleweli/tackup/commit/bda3928eb69a70f1aaab6ccacd5b6bea58c1c128), the first is accessible through the standard config page under after checking the "Auto-delete backups" box, the other by following the "Remove tabsets…" link at the bottom.

If you could check if these work for you (I'd recommend exporting a back-up beforehand, just in case), that'd be great!

**Comment by nabijaczleweli** [comment]
Older/newer-than, too, while at it

**Comment by ghost** [comment]
Hi, sorry about the delayed response, my SSD died so I was busy setting everything up again, hope you're doing well. I've just tried it and all added features seems to work pretty well, thanks!

**Comment by grahamperrin** [comment]
I like this idea, will an updated extension be published at AMO?

**Comment by nabijaczleweli** [comment]
I was waiting on #5 before releasing, but it worked in my testing, so I'll push it now

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.3.0)
