### ISSUE TITLE
Don't make duplicate backups if the list of tabs did not change

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/tackup#5]
Would you consider adding a feature so the extension will skip the backup if the list of tabs remain exactly the same as the previous backup? I think it might be useful for people who like to set the interval to a pretty low value.

**Comment by nabijaczleweli** [comment]
Does [latest `master`](https://github.com/nabijaczleweli/tackup/commit/702382eb5225fdbbcfeedc8f86738bcce6cf7216) works for you?

**Comment by ghost** [comment]
Thanks for the change, so far I think it partially. If I delete all tab sets, the plugin throws and error and stops working.
<img width="1264" alt="2" src="https://user-images.githubusercontent.com/39971507/60922207-d14da480-a2ce-11e9-8473-91d3f7605c7c.png">

**Comment by nabijaczleweli** [comment]
Oops, missed that case! [Current `master`](https://github.com/nabijaczleweli/tackup/commit/5fb55f29d5cb359e849b4c10ae3cc8ac6dad747c) should contain a fix?

**Comment by nabijaczleweli** [comment]
Released in [`v0.3.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.3.0)
