### ISSUE TITLE
0.3.0: "Don't duplicate the freshest backup" will not stay checked

### ISSUE THREAD

**Issue by ghost** [nabijaczleweli/tackup#8]
If the preferences page is refreshed, the box will become unchecked once again. 

Also occasionally the extension will stop working after the config has been saved for some reason, sadly I can't provide more info as I can't reliably reproduce it, and I didn't see any errors in console, either. 

Edit: it appears that the extension simply didn't apply the new config immediately, so if I set a long interval (i.e. 10 minutes), save, and then change it to 2 seconds, it'll wait for 10 minutes and then switch the interval to 2 seconds.

**Comment by nabijaczleweli** [comment]
Hmm, the config should be saved and able to be seen immediately – can you open the debug/browser console and see if you get a "Config set!" or a "Configuration setting error" message when clicking Save?

As for the timing: yes, that's unfortunately an issue I haven't come up with a good solution to, the saving thread has no way of knowing that there was a new delay applied until it saves and reads the config again.

**Comment by ghost** [comment]
"Config set!" was printed to the console after clicking Save, and then the box will become unchecked once again after refreshing about:addons. The bit was actually still set as I can see the duplicates being ignored in the log.

**Comment by nabijaczleweli** [comment]
Ah yeah, I used the wrong member on the checkbox lol, will release fix shortly, and thanks for the report!

**Comment by ghost** [comment]
👌 thanks for the fix

**Comment by nabijaczleweli** [comment]
Released in [`v0.4.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.4.0)
