### ISSUE TITLE
Open selected items in new tabs

### ISSUE THREAD

**Issue by grahamperrin** [nabijaczleweli/tackup#9]
After presenting a list of tabs, I sometimes need to open some or all (not just one) of the listed items. 

Is it possible to enhance the user interface, to allow this? 

Maybe a complementary extension can serve the purpose, but I'm not aware of one for Firefox Quantum. 

(With Waterfox Classic 2019.10, I use legacy [Snap Links Plus](https://web.archive.org/web/20160506224225/https://addons.mozilla.org/en-US/firefox/addon/SnapLinksPlus/) 2.4.3, which can work with special pages.)

**Comment by nabijaczleweli** [comment]
Do the changes in the referenced commit work for you?

**Comment by nabijaczleweli** [comment]
Released in [`v0.5.0`](https://github.com/nabijaczleweli/tackup/releases/tag/v0.5.0).

**Comment by grahamperrin** [comment]
Thanks, and apologies for not responding in 2019 … I probably lost sight of this whilst moving away from Waterfox to Firefox,
